### ISSUE TITLE
Option "Export dataset" doesn't work

### ISSUE THREAD

**Issue by kateryna-polishchuk** [artbels/mongo-table-admin#1]
Download fails with "Network error" (OS Ubuntu 14.04)

**Comment by artbels** [comment]
Please check that you have the latest version installed. If does not help, please attach JS console screenshot.

**Comment by kotomoika** [comment]
http://res.cloudinary.com/ddb6woz5u/image/upload/c_scale,w_1296/v1471955316/problems/exportdatasetProblem.png

**Comment by artbels** [comment]
Swithed to download.js, check if it helps.
